name: ananta_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  file_picker: ^10.3.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/ananta_portf/
    - lib/assets/theme_cards/
    - lib/assets/sponsor_visibility/
